parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: root
    database_password: sergiop
    mailer_transport: smtp
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: sergiop18
    mailer_password: checho6
    locale: en
    secret: 5cf841e9a8e6f293367655fad566b935
    database_path: null
