parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     null
    database_name:     cupon
    database_user:     root
    database_password: sergiop

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
